package com.plexon.homes.api;

public enum HomeTeleportStatus {
    STARTED,
    TELEPORTED,
    PERMISSION_DENIED,
    HOME_NOT_FOUND,
    LIMIT_RESTRICTED,
    ALREADY_PENDING,
    COOLDOWN,
    WORLD_BLOCKED,
    UNSAFE_DESTINATION,
    ECONOMY_UNAVAILABLE,
    INSUFFICIENT_FUNDS,
    CANCELLED,
    FAILED
}
